# Generated by Django 5.2.5 on 2026-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Haymanot Asmare', max_length=100)),
                ('title', models.CharField(default='Full Stack Software Engineer', max_length=200)),
                ('bio', models.TextField(default="I'm a passionate Full Stack Software Engineer with extensive experience in building scalable web applications and creating exceptional digital experiences. My expertise spans across modern frontend frameworks, robust backend systems, and intuitive UI/UX design.")),
                ('detailed_bio', models.TextField(default='I specialize in transforming complex business requirements into elegant, efficient solutions that drive measurable results. With a strong foundation in both engineering and design principles, I bridge the gap between technical implementation and user experience.')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('years_experience', models.PositiveIntegerField(default=5)),
                ('projects_delivered', models.PositiveIntegerField(default=50)),
                ('happy_clients', models.PositiveIntegerField(default=30)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('upwork_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
